### PR TITLE
Matchwoparse

### PR DESCRIPTION
**Pull request by auroredea**
- I made some modifications because I want to dynamically determine the trait CSV or Tab depending on the extension. I will search for a better implementation (needed..)
- Now on `match` command, it will only match based on the tree resulting to `parse` command.

### CODE REVIEW

**Comment by pwolff** [comment]
Hi Aurore,
   This is excellent! I can’t wait to use it.
Phil

**Comment by windweller** [comment]
When you did enough changes or finalize your command-line, we should have a new release!

**Comment by auroredea** [comment]
I am waiting for the review of Phillip, but yep, good idea Allen :+1: !
Let me change the README file before.

**Comment by pwolff** [comment]
Hi Aurore,
   I won’t be able to get to this until Wednesday (because of a grant submission). I’m really looking forward to trying it!
Phil

**Comment by auroredea** [comment]
Thank you Phil, we keep in touch.

**Pull request merged**
